# pytorch基础

In [2]:
import numpy as np
import torch

In [44]:
# 清空所有的变量
%reset -f

## tensor API

### 创建tensor

In [3]:
# 列表转tensor
a = [1, 3, 5]
b = torch.Tensor(a)
display(b, b.type)

tensor([1., 3., 5.])

<function Tensor.type>

In [24]:
# 元组转tensor
d = torch.tensor(((1, 2), (3, 4)))
display(d)
display(d.type())

tensor([[1, 2],
        [3, 4]])

'torch.LongTensor'

In [4]:
# 使用numpy转tensor
torch.tensor(np.arange(15).reshape(3,5))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [5]:
# empty api
torch.empty([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
# ones api
torch.ones([3,4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
d = torch.ones_like(torch.ones([3,4]))
display(d)
display(d.type())

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

'torch.FloatTensor'

In [7]:
# zeros api
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# zeros_like api
d = torch.zeros_like(torch.zeros([3,4]))
display(d)
display(d.type())

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

'torch.FloatTensor'

In [27]:
# eye api(单位矩阵)
d = torch.eye(2, 2)
display(d)
display(d.type())

tensor([[1., 0.],
        [0., 1.]])

'torch.FloatTensor'

In [8]:
# 高斯分布的tensor
a = np.random.rand(2, 3)
display(a, a.dtype)
b = torch.Tensor(a)
display(b, b.type, b.dtype)

array([[0.94651651, 0.8413694 , 0.69195422],
       [0.31956688, 0.58783865, 0.97428372]])

dtype('float64')

tensor([[0.9465, 0.8414, 0.6920],
        [0.3196, 0.5878, 0.9743]])

<function Tensor.type>

torch.float32

In [29]:
# tensor的高斯分布api
d = torch.rand(2, 3)
display(d)
display(d.type())

tensor([[0.1420, 0.6133, 0.9628],
        [0.6327, 0.8919, 0.3087]])

'torch.FloatTensor'

In [32]:
# 创建一个mean = 0, std = 1的高斯分布
dd = torch.normal(mean=0, std=1, size=(2, 3), out = b)
display(b)
display(dd)

tensor([[ 0.4989, -1.2839, -0.1729],
        [-2.1871, -0.2828,  0.0365]])

tensor([[ 0.4989, -1.2839, -0.1729],
        [-2.1871, -0.2828,  0.0365]])

In [33]:
# 使用uniform创建一个-1到1的均匀分布的随机数
d = torch.Tensor(2, 2).uniform_(-1, 1)
display(d)
display(d.type())

tensor([[-0.2582, -0.8671],
        [ 0.6809, -0.8624]])

'torch.FloatTensor'

In [35]:
# 返回从0到指定范围的随机数
d = torch.randperm(10)
display(d)
display(d.type())

tensor([0, 3, 8, 9, 5, 2, 1, 7, 4, 6])

'torch.LongTensor'

In [9]:
# 使用torch的arange
a = torch.arange(start=1, end=10, step=3)
display(a, a.dtype)

tensor([1, 4, 7])

torch.int64

In [30]:
# 序列tensor
d = torch.linspace(10, 2, 3)
display(d)
display(d.type())

tensor([10.,  6.,  2.])

'torch.FloatTensor'

In [ ]:
# torch.full
a = torch.full((2, 3), 3)
print(a, a.type, a.dtype)

tensor([[3, 3, 3],
        [3, 3, 3]]) <built-in method type of Tensor object at 0x0000028A540E2F90> torch.int64


In [43]:
# 随机种子
torch.manual_seed(1)
mean = torch.rand(1, 2)
std  = torch.rand(1, 2)
display(torch.normal(mean, std))

tensor([[0.7825, 0.7358]])

### tensor的属性和方法

In [2]:
# 获取tensor的值
a = torch.tensor([[[1]]])
display(a)
display(a.item())

tensor([[[1]]])

1

In [3]:
# 转成numpy
t = a.numpy()
type(t)

numpy.ndarray

In [4]:
# 获取其大小
display(a.shape, a.size())

torch.Size([1, 1, 1])

torch.Size([1, 1, 1])

In [7]:
# 获取某个维度的值
a = torch.tensor(np.arange(30).reshape(3,2,5))
display(a)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [8]:
# 获取第一个维度的样本量
display(a.size(1))

2

In [9]:
# 对tensor进行视图（转成2，3，5） 不改变内存，只改变步长和形状
a.view([2,3,5])

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [8]:
# 进行维度交换
b = torch.tensor(np.arange(15).reshape(3,5))
display(b)
# 进行维度交换
display(torch.t(b))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]], dtype=torch.int32)

In [11]:
# 直接交换行和列
b.transpose(0, 1)  

tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]], dtype=torch.int32)

In [12]:
# torch.squeeze 用于从张量中移除维度为 1 的维度
# torch.unsqueeze 用于在张量中插入维度为 1 的维度
a = torch.rand(2, 3, 1)
display(a)
out = torch.squeeze(a)
display(out)
display(out.shape)
out = torch.unsqueeze(a, -1)
display(out)
display(out.shape)

tensor([[[0.1643],
         [0.0967],
         [0.1936]],

        [[0.7837],
         [0.9381],
         [0.7215]]])

tensor([[0.1643, 0.0967, 0.1936],
        [0.7837, 0.9381, 0.7215]])

torch.Size([2, 3])

tensor([[[[0.1643]],

         [[0.0967]],

         [[0.1936]]],


        [[[0.7837]],

         [[0.9381]],

         [[0.7215]]]])

torch.Size([2, 3, 1, 1])

In [13]:
# torch.unbind 是 PyTorch 中用于在指定维度上解绑张量的函数,并返回元组
out = torch.unbind(a, dim=2)
display(out)

(tensor([[0.1643, 0.0967, 0.1936],
         [0.7837, 0.9381, 0.7215]]),)

In [18]:
# 沿着指定维度翻转（反转）张量的元素顺序
a = torch.rand(2, 3)
display(a)
display(torch.flip(a, dims=[1, 0]))

tensor([[0.1825, 0.1139, 0.5893],
        [0.2744, 0.1487, 0.4156]])

tensor([[0.4156, 0.1487, 0.2744],
        [0.5893, 0.1139, 0.1825]])

In [19]:
# 用于将张量沿着指定维度进行逆时针旋转90度，旋转k次
a = torch.rand(2, 3)
out = torch.rot90(a, -1, dims=[0, 1])

In [12]:
# 把b展开之后等分为5分
b.view(5,-1) 

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [16]:
# 获取tensor某个维度的值
display(b[1, :])
display(b[1])
display(b[:,1])

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

tensor([ 1,  6, 11], dtype=torch.int32)

In [17]:
# 以广播的形式为选中元素赋值
b[:, 1] = 100
display(b)

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13,  14]], dtype=torch.int32)

In [18]:
# 为单个元素赋值
b[-1, -1] = 100
display(b)

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [23]:
# 转换tensor的数据格式
display(torch.FloatTensor([1,2,3]).dtype)

torch.float32

In [24]:
# 初始化tensor是设置数据格式
display(torch.ones([2,3],dtype=torch.float32))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [26]:
# 对原有tensor进行初始化
display(b.new_ones(size=b.size()))
display(b.zero_())

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [27]:
# 以广播的形式对tensor进行+1
display(b.add(1))  # 复制+
display(b.add_(1)) # 原地+

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

### cuda类型的tensor

In [28]:
# 获取cuda
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") 
display(device)

device(type='cuda')

In [35]:
# 将cpu的tensor转到gpu上
a = torch.tensor([1, 1, 1], dtype=float)
display(a.device)
a = a.to(device)
display(a.device)
display(a)

device(type='cpu')

device(type='cuda', index=0)

tensor([1., 1., 1.], device='cuda:0', dtype=torch.float64)

In [36]:
# 将cuda转到cpu
display(a.cpu().device)

device(type='cpu')

In [37]:
# cpu上的tensor和gpu上的tensor进行+
b = torch.tensor([0,0,0])
display(a + b.to(device)) # 会到gpu上

tensor([1., 1., 1.], device='cuda:0', dtype=torch.float64)

### tensor的属性和方法

In [3]:
# clamp对tensor数据设置取值范围
a = torch.rand(2, 2) * 10
display(a)
a = a.clamp(2, 5)
display(a)

tensor([[1.1095, 9.5109],
        [9.5415, 1.6618]])

tensor([[2., 5.],
        [5., 2.]])

In [5]:
# tensor的广播 加到每一行
a = torch.rand(2, 2)
b = torch.rand(1, 2)
c = a + b
display(a)
display(b)
display(c)
display(c.shape)

tensor([[0.5350, 0.8068],
        [0.9854, 0.1264]])

tensor([[0.3737, 0.4212]])

tensor([[0.9087, 1.2280],
        [1.3591, 0.5476]])

torch.Size([2, 2])

In [6]:
# tensor之间的比较
a = torch.rand(2, 3)
b = torch.rand(2, 3)
display(a, b)

display(torch.eq(a, b))
display(torch.equal(a, b))

display(torch.ge(a, b))  # >=
display(torch.gt(a, b))  # >
display(torch.le(a, b))  # <=
display(torch.lt(a, b))  # <
display(torch.ne(a, b))  # !=

tensor([[0.0262, 0.1459, 0.9889],
        [0.5878, 0.7082, 0.6546]])

tensor([[0.4083, 0.6137, 0.1125],
        [0.8795, 0.1412, 0.1745]])

tensor([[False, False, False],
        [False, False, False]])

False

tensor([[False, False,  True],
        [False,  True,  True]])

tensor([[False, False,  True],
        [False,  True,  True]])

tensor([[ True,  True, False],
        [ True, False, False]])

tensor([[ True,  True, False],
        [ True, False, False]])

tensor([[True, True, True],
        [True, True, True]])

In [7]:
# tensor的排序
a = torch.tensor([[1, 4, 4, 3, 5],
                  [2, 3, 1, 3, 5]])
display(a.shape)
display(torch.sort(a, dim=1, descending=False))

torch.Size([2, 5])

torch.return_types.sort(
values=tensor([[1, 3, 4, 4, 5],
        [1, 2, 3, 3, 5]]),
indices=tensor([[0, 3, 1, 2, 4],
        [2, 0, 1, 3, 4]]))

In [11]:
# 查找前tensor的最大(小)的k个值，并返回下标
a = torch.tensor([[2, 4, 3, 1, 5],
                  [2, 3, 5, 1, 4]])
display(a.shape)
display(torch.topk(a, k = 2, dim=1, largest=False))

torch.Size([2, 5])

torch.return_types.topk(
values=tensor([[1, 2],
        [1, 2]]),
indices=tensor([[3, 0],
        [3, 0]]))

In [ ]:
# 第k小（或第k大）的值，而不返回对应的索引。
display(torch.kthvalue(a, k=2, dim=0))
display(torch.kthvalue(a, k=2, dim=1))

torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))

torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))

In [13]:
# tensor的取值
a = torch.rand(2, 3)
print(a)
print(a/0)
print(torch.isfinite(a))
print(torch.isfinite(a/0))
print(torch.isinf(a/0))
print(torch.isnan(a))

tensor([[0.4513, 0.8150, 0.1886],
        [0.2309, 0.1703, 0.5045]])
tensor([[inf, inf, inf],
        [inf, inf, inf]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [15]:
# 判断是否为numpy中的非数值
a = torch.tensor([1, 2, np.nan])
print(a)
print(torch.isnan(a))

tensor([1., 2., nan])
tensor([False, False,  True])


In [26]:
# 用于将输入张量沿着指定维度进行分块
a = torch.rand((3, 4))
display(a)
out = torch.chunk(a, 2, dim=1)
display(out[0], out[0].shape)
display(out[1], out[1].shape)

tensor([[0.9023, 0.7209, 0.6406, 0.3282],
        [0.6025, 0.8401, 0.1511, 0.8847],
        [0.5466, 0.8626, 0.6166, 0.8416]])

tensor([[0.9023, 0.7209],
        [0.6025, 0.8401],
        [0.5466, 0.8626]])

torch.Size([3, 2])

tensor([[0.6406, 0.3282],
        [0.1511, 0.8847],
        [0.6166, 0.8416]])

torch.Size([3, 2])

In [27]:
a = torch.rand((10, 4))
display(a)
out = torch.split(a, 3, dim=0)
display(len(out))
for t in out:
    display(t, t.shape)

out = torch.split(a, [1, 3, 6], dim=0)
for t in out:
    display(t, t.shape)

tensor([[0.9251, 0.3730, 0.3715, 0.8856],
        [0.5826, 0.2469, 0.8072, 0.5046],
        [0.0789, 0.4340, 0.6834, 0.8746],
        [0.0714, 0.9318, 0.5716, 0.3496],
        [0.0279, 0.5919, 0.7209, 0.3265],
        [0.0662, 0.4997, 0.9798, 0.1893],
        [0.1890, 0.4692, 0.3342, 0.7685],
        [0.8841, 0.5261, 0.2210, 0.0932],
        [0.2867, 0.0605, 0.8225, 0.1724],
        [0.7335, 0.7447, 0.5862, 0.8193]])

4

tensor([[0.9251, 0.3730, 0.3715, 0.8856],
        [0.5826, 0.2469, 0.8072, 0.5046],
        [0.0789, 0.4340, 0.6834, 0.8746]])

torch.Size([3, 4])

tensor([[0.0714, 0.9318, 0.5716, 0.3496],
        [0.0279, 0.5919, 0.7209, 0.3265],
        [0.0662, 0.4997, 0.9798, 0.1893]])

torch.Size([3, 4])

tensor([[0.1890, 0.4692, 0.3342, 0.7685],
        [0.8841, 0.5261, 0.2210, 0.0932],
        [0.2867, 0.0605, 0.8225, 0.1724]])

torch.Size([3, 4])

tensor([[0.7335, 0.7447, 0.5862, 0.8193]])

torch.Size([1, 4])

tensor([[0.9251, 0.3730, 0.3715, 0.8856]])

torch.Size([1, 4])

tensor([[0.5826, 0.2469, 0.8072, 0.5046],
        [0.0789, 0.4340, 0.6834, 0.8746],
        [0.0714, 0.9318, 0.5716, 0.3496]])

torch.Size([3, 4])

tensor([[0.0279, 0.5919, 0.7209, 0.3265],
        [0.0662, 0.4997, 0.9798, 0.1893],
        [0.1890, 0.4692, 0.3342, 0.7685],
        [0.8841, 0.5261, 0.2210, 0.0932],
        [0.2867, 0.0605, 0.8225, 0.1724],
        [0.7335, 0.7447, 0.5862, 0.8193]])

torch.Size([6, 4])

### 处理多个tensor的方法

In [20]:
# torch.cat组合两个tensor（不会创建新的维度）
a = torch.zeros((2, 4))
b = torch.ones((2, 4))
out1 = torch.cat((a,b), dim=0)
display(out1)
out2 = torch.cat((a,b), dim=1)
display(out2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]])

In [22]:
# torch.stack创建新的维度堆叠tensor
a = torch.linspace(1, 6, 6).view(2, 3)
b = torch.linspace(7, 12, 6).view(2, 3)
display(a, b)
out = torch.stack((a, b), dim=2)
display(out)
display(out.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])

torch.Size([2, 3, 2])

In [48]:
# 计算两个tensor的欧式距离
a = torch.rand(2, 1)
b = torch.rand(2, 1)
display(a, b)
display(torch.dist(a, b, p = 1))
display(torch.dist(a, b, p = 2))
display(torch.dist(a, b, p = 3))

display(torch.norm(a))
display(torch.norm(a, p=3))
display(torch.norm(a, p='fro'))

tensor([[0.3958],
        [0.1515]])

tensor([[0.3623],
        [0.5476]])

tensor(0.4296)

tensor(0.3975)

tensor(0.3962)

tensor(0.4238)

tensor(0.4030)

tensor(0.4238)

In [3]:
"""
    torch.floor：将张量中的元素向下取整，得到不大于原值的最大整数。
    torch.ceil：将张量中的元素向上取整，得到不小于原值的最小整数。
    torch.round：将张量中的元素四舍五入为最接近的整数。
    torch.trunc：将张量中的元素截断取整，保留整数部分。
    torch.frac：提取张量中元素的小数部分。
    torch.fmod：对两个张量的元素进行模运算，返回的结果具有与被除数相同的符号。这意味着在模运算时，结果的符号与被除数的符号保持一致。
    torch.remainder：对两个张量的元素进行模运算，返回的结果具有与除数相同的符号。这意味着在模运算时，结果的符号与除数的符号保持一致。
"""
a = torch.rand(2, 2)
a = a * 10
display(a)

display(torch.floor(a))
display(torch.ceil(a))
display(torch.round(a))
display(torch.trunc(a))
display(torch.frac(a))
display(a % 2)
b = torch.tensor([[2, 3], [4, 5]], dtype=torch.float)
display(torch.fmod(a, b))
display(torch.remainder(a, b))

tensor([[4.0532, 5.1024],
        [8.7267, 8.8768]])

tensor([[4., 5.],
        [8., 8.]])

tensor([[5., 6.],
        [9., 9.]])

tensor([[4., 5.],
        [9., 9.]])

tensor([[4., 5.],
        [8., 8.]])

tensor([[0.0532, 0.1024],
        [0.7267, 0.8768]])

tensor([[0.0532, 1.1024],
        [0.7267, 0.8768]])

tensor([[0.0532, 2.1024],
        [0.7267, 3.8768]])

tensor([[0.0532, 2.1024],
        [0.7267, 3.8768]])

In [4]:
# tensor之间相加
a = torch.rand(2, 3)
b = torch.rand(2, 3)

display(a, b)
display(a + b)
display(a.add(b))
display(torch.add(a, b))
display(a)
display(a.add_(b))
display(a)

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.0506, 0.3802, 0.9635],
        [0.7589, 0.3405, 0.0539]])

tensor([[0.3014, 0.4968, 1.1735],
        [1.3661, 0.4125, 0.6147]])

tensor([[0.3014, 0.4968, 1.1735],
        [1.3661, 0.4125, 0.6147]])

tensor([[0.3014, 0.4968, 1.1735],
        [1.3661, 0.4125, 0.6147]])

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.3014, 0.4968, 1.1735],
        [1.3661, 0.4125, 0.6147]])

tensor([[0.3014, 0.4968, 1.1735],
        [1.3661, 0.4125, 0.6147]])

In [5]:
# tensor相减
display(a - b)
display(torch.sub(a, b))
display(a.sub(b))
display(a.sub_(b))
display(a)

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

In [12]:
# tensor数位相乘
a = torch.rand(1, 2)
b = torch.rand(1, 2)
display(a, b)
display(a * b)
display(torch.mul(a, b))
display(a.mul(b))
display(a)
display(a.mul_(b))
display(a)

tensor([[0.2959, 0.6185]])

tensor([[0.7581, 0.0541]])

tensor([[0.2243, 0.0335]])

tensor([[0.2243, 0.0335]])

tensor([[0.2243, 0.0335]])

tensor([[0.2959, 0.6185]])

tensor([[0.2243, 0.0335]])

tensor([[0.2243, 0.0335]])

In [7]:
# tensor相除
display(a/b)
display(torch.div(a, b))
display(a.div(b))
display(a.div_(b))
display(a)

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

tensor([[0.2508, 0.1166, 0.2100],
        [0.6073, 0.0720, 0.5608]])

In [10]:
# tensor的矩阵乘法
a = torch.rand(2, 1)
b = torch.rand(1, 2)
display(a, b)
display(a @ b)
display(a.matmul(b))
display(torch.matmul(a, b))
display(torch.mm(a, b))
display(a.mm(b))

tensor([[0.3134],
        [0.4251]])

tensor([[0.1687, 0.3888]])

tensor([[0.0529, 0.1219],
        [0.0717, 0.1653]])

tensor([[0.0529, 0.1219],
        [0.0717, 0.1653]])

tensor([[0.0529, 0.1219],
        [0.0717, 0.1653]])

tensor([[0.0529, 0.1219],
        [0.0717, 0.1653]])

tensor([[0.0529, 0.1219],
        [0.0717, 0.1653]])

In [2]:
# 多维矩阵相乘，只乘最后两维，但前面维数要一样
x = torch.ones(4, 3, 2, 3)
y = torch.ones(4, 3, 3, 3)
display(x.size(), y.size())
c = torch.matmul(x, y)
display(c.size())

torch.Size([4, 3, 2, 3])

torch.Size([4, 3, 3, 3])

torch.Size([4, 3, 2, 3])

In [ ]:
a = torch.randn(2,3)
print(a)
a = a.mul(0.5).exp()
print(a)

tensor([[-0.7881, -1.6043,  0.6394],
        [ 1.6493,  0.4991, -0.9075]])
tensor([[0.6743, 0.4484, 1.3767],
        [2.2811, 1.2835, 0.6352]])


In [3]:
# tensor的乘方
a = torch.tensor([1, 2])
display(torch.pow(a, 3))
display(a.pow(3))
display(a**3)
display(a.pow_(3))
display(a)

tensor([1, 8])

tensor([1, 8])

tensor([1, 8])

tensor([1, 8])

tensor([1, 8])

In [4]:
# exp
a = torch.tensor([1, 2],
                 dtype=torch.float32)
display(a.type())
display(torch.exp(a))
display(torch.exp_(a))
display(a.exp())
display(a.exp_())

'torch.FloatTensor'

tensor([2.7183, 7.3891])

tensor([2.7183, 7.3891])

tensor([  15.1543, 1618.1781])

tensor([  15.1543, 1618.1781])

In [5]:
# log
a = torch.tensor([10, 2],
                 dtype=torch.float32)
display(torch.log(a))
display(torch.log_(a))
display(a.log())
display(a.log_())

tensor([2.3026, 0.6931])

tensor([2.3026, 0.6931])

tensor([ 0.8340, -0.3665])

tensor([ 0.8340, -0.3665])

In [6]:
# sqrt
a = torch.tensor([10, 2],
                 dtype=torch.float32)
display(torch.sqrt(a))
display(torch.sqrt_(a))
display(a.sqrt())
display(a.sqrt_())

tensor([3.1623, 1.4142])

tensor([3.1623, 1.4142])

tensor([1.7783, 1.1892])

tensor([1.7783, 1.1892])

In [29]:
# tensor的统计方法
a = torch.rand(2, 2)
display(a)
display(torch.mean(a, dim=0))
display(torch.sum(a, dim=0))
display(torch.prod(a, dim=0))

display(torch.argmax(a, dim=0))
display(torch.argmin(a, dim=0))

display(torch.std(a))
display(torch.var(a))

display(torch.median(a)) # 中位数
display(torch.mode(a))   # 众数

tensor([[0.5415, 0.2105],
        [0.0983, 0.0866]])

tensor([0.3199, 0.1485])

tensor([0.6398, 0.2971])

tensor([0.0532, 0.0182])

tensor([0, 0])

tensor([1, 1])

tensor(0.2123)

tensor(0.0451)

tensor(0.0983)

torch.return_types.mode(
values=tensor([0.2105, 0.0866]),
indices=tensor([1, 1]))

In [30]:
# 计算张量中元素的直方图的函数
a = torch.rand(2, 2) * 10
display(a)
display(torch.histc(a, 6, 0, 0))

tensor([[4.8908, 8.8141],
        [1.5951, 8.8134]])
tensor([1., 0., 1., 0., 0., 2.])


In [36]:
# 非负整数张量中每个值出现的频次的函数。它返回一个张量，其中索引表示数值，而对应的值表示该数值在输入张量中出现的次数
a = torch.tensor([0, 1, 2, 1, 0, 2, 1, 2, 2])
display(a)
display(torch.bincount(a))

tensor([0, 1, 2, 1, 0, 2, 1, 2, 2])

tensor([2, 3, 4])

In [38]:
# 三角函数
a = torch.zeros(2, 3)
b = torch.cos(a)
print(a)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### 索引操作

In [20]:
# torch.where进行条件判断
a = torch.rand(4, 4)
b = torch.rand(4, 4)
display(a, b)
out = torch.where(a > 0.5, a, b)
display(out)

tensor([[0.0525, 0.9850, 0.4007, 0.5261],
        [0.5777, 0.3308, 0.8032, 0.5887],
        [0.4958, 0.2491, 0.2358, 0.7320],
        [0.4340, 0.7606, 0.6815, 0.9837]])

tensor([[0.4426, 0.4344, 0.1903, 0.7261],
        [0.2721, 0.8383, 0.9600, 0.7061],
        [0.8926, 0.4639, 0.9388, 0.3535],
        [0.1596, 0.8712, 0.8780, 0.6849]])

tensor([[0.4426, 0.9850, 0.1903, 0.5261],
        [0.5777, 0.8383, 0.8032, 0.5887],
        [0.8926, 0.4639, 0.9388, 0.7320],
        [0.1596, 0.7606, 0.6815, 0.9837]])

In [21]:
# 根据索引选择tensor
a = torch.rand(4, 4)
display(a)
out = torch.index_select(a, dim=0,
                   index=torch.tensor([0, 3, 2]))

display(out, out.shape)

tensor([[0.4222, 0.0403, 0.1243, 0.7992],
        [0.3825, 0.1122, 0.8113, 0.8258],
        [0.6755, 0.4806, 0.8409, 0.1232],
        [0.7096, 0.7113, 0.2379, 0.4624]])

tensor([[0.4222, 0.0403, 0.1243, 0.7992],
        [0.7096, 0.7113, 0.2379, 0.4624],
        [0.6755, 0.4806, 0.8409, 0.1232]])

torch.Size([3, 4])

In [22]:
# 根据给定的索引从输入张量中收集指定位置的元素
a = torch.linspace(1, 16, 16).view(4, 4)
display(a)
out = torch.gather(a, dim=0,
             index=torch.tensor([[0, 1, 1, 1],
                                 [0, 1, 2, 2],
                                 [0, 1, 3, 3]]))
display(out, out.shape)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.],
        [ 1.,  6., 15., 16.]])

torch.Size([3, 4])

In [23]:
# 根据掩码选择tensor中的值
a = torch.linspace(1, 16, 16).view(4, 4)
mask = torch.gt(a, 8)
display(a)
display(mask)
out = torch.masked_select(a, mask)
display(out)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])

In [24]:
# 根据索引选择tensor的值(将输入张量扁平化为一维，然后根据索引获取元素。)
a = torch.linspace(1, 16, 16).view(4, 4)
b = torch.take(a, index=torch.tensor([0, 15, 13, 10]))
display(a, b)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

tensor([ 1., 16., 14., 11.])

In [25]:
# 找到张量中非零元素的索引。它返回一个张量，其中每一行都包含一个非零元素的索引
a = torch.tensor([[0, 1, 2, 0], [2, 3, 0, 1]])
out = torch.nonzero(a)
display(a, out)

tensor([[0, 1, 2, 0],
        [2, 3, 0, 1]])

tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 3]])

## torch.nn API

In [ ]:
import torch

### nn.Embedding

In [ ]:
"""
一个简单的查找表（lookup table），存储固定字典和大小的词嵌入。
此模块通常用于存储单词嵌入并使用索引检索它们(类似数组)。模块的输入是一个索引列表，输出是相应的词嵌入。
num_embeddings - 词嵌入字典大小，即一个字典里要有多少个词。
embedding_dim - 每个词嵌入向量的大小。
"""

'\n一个简单的查找表（lookup table），存储固定字典和大小的词嵌入。\n此模块通常用于存储单词嵌入并使用索引检索它们(类似数组)。模块的输入是一个索引列表，输出是相应的词嵌入。\nnum_embeddings - 词嵌入字典大小，即一个字典里要有多少个词。\nembedding_dim - 每个词嵌入向量的大小。\n'

In [ ]:
# 设置一个字典长10，词向量长度为3的词嵌入
embedding = torch.nn.Embedding(10, 3)
embedding

Embedding(10, 3)

In [ ]:
# 数字是样本编号索引，每一个是一个长度为3的索引
# [1,2,4,5]表示一个句子列表，数字表示词
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
embedding(input)

tensor([[[-0.0970, -2.3749,  1.6615],
         [-1.0845,  0.4108,  0.2650],
         [ 0.4780,  0.4143,  0.6528],
         [ 0.2218,  0.7237, -2.5136]],

        [[ 0.4780,  0.4143,  0.6528],
         [ 0.9073,  0.4980,  0.4852],
         [-1.0845,  0.4108,  0.2650],
         [-0.0905,  0.3385, -0.0089]]], grad_fn=<EmbeddingBackward0>)

In [ ]:
# example with padding_idx
embedding = torch.nn.Embedding(10, 3, padding_idx=0)
input1 = torch.LongTensor([[0, 2, 0, 5]])
embedding(input1)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [-1.0514e+00,  5.8627e-04, -4.3436e-01],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 1.3114e+00, -1.3614e+00,  1.0755e+00]]],
       grad_fn=<EmbeddingBackward0>)

In [ ]:
# example of changing `pad` vector
embedding = torch.nn.Embedding(3, 3, padding_idx=0)
embedding.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.6744,  0.4043,  0.8073],
        [ 0.2897,  0.6995,  0.3052]], requires_grad=True)

In [ ]:
# 进行权重预训练（初始为高斯分布权重）
embedding = torch.nn.init.normal_(embedding.weight, 0, 1)
print(embedding)

Parameter containing:
tensor([[-0.3360,  1.0078,  0.5159],
        [-0.8106,  0.3944, -1.5112],
        [ 0.5663, -1.3853,  0.1288]], requires_grad=True)


### nn.Dropout

In [ ]:
"""
概率不激活神经元
p:表示不激活的概率
"""

'\n概率不激活神经元\np:表示不激活的概率\n'

In [ ]:
m = torch.nn.Dropout(p=0.3)
input = torch.randn(4, 3)
print(input)
print(m(input))

tensor([[-0.5549,  0.1655, -0.1474],
        [-0.0985, -0.8826, -0.4346],
        [ 0.0348,  0.6007,  0.5137],
        [ 1.1078,  0.6560,  1.9803]])
tensor([[-0.0000,  0.0000, -0.2105],
        [-0.1407, -1.2608, -0.6208],
        [ 0.0497,  0.8581,  0.0000],
        [ 1.5826,  0.9371,  2.8289]])


In [ ]:
m = torch.nn.Conv1d(16, 33, 3, stride=2)  # 输入16，输出33
input = torch.randn(20, 16, 50)  # 批量为20，样本个数为16，长度为50的词向量
m(input)

tensor([[[-0.2949, -0.3116,  0.6805,  ...,  0.1820, -1.4174,  0.2907],
         [ 1.2465, -0.9830, -0.1022,  ...,  0.2662,  0.5109, -0.5642],
         [-0.0626, -0.3004,  0.0111,  ..., -0.0970, -0.2090,  0.3865],
         ...,
         [ 0.2609,  0.3006,  0.4918,  ...,  0.2009,  0.2093,  0.3688],
         [-0.4449, -0.1258, -0.6255,  ...,  0.2226, -0.9251, -0.1009],
         [ 0.7110,  0.2450, -0.8216,  ..., -0.7978,  0.0033, -0.1864]],

        [[ 0.9564,  0.2986,  0.6767,  ..., -0.2930,  0.0050,  0.0429],
         [-0.2552,  0.3730, -0.2167,  ..., -0.0464,  1.2453,  0.4323],
         [ 0.2728,  0.5488,  0.0951,  ..., -0.5268,  1.1085,  0.1429],
         ...,
         [-0.1823,  0.6875,  1.2736,  ...,  0.8126,  0.6698,  0.2496],
         [-0.2675, -0.2753,  0.2984,  ..., -0.2252,  0.2771,  0.4653],
         [-0.5681,  0.2002,  0.1237,  ...,  0.2349, -1.1563, -0.6949]],

        [[-1.1437, -0.6525,  0.6027,  ..., -0.1978,  0.1055, -0.8331],
         [-0.0048, -0.5421,  0.4392,  ...,  0

In [ ]:
n = torch.nn.Conv1d(5, 4, 2)  # kernel_size = 2
input = torch.randn(3, 5, 5)
n(input)

tensor([[[-6.2543e-01, -6.4423e-01,  5.7986e-01, -6.2900e-01],
         [ 5.4330e-01,  1.9020e-01, -4.0227e-01,  1.2573e-01],
         [ 1.6384e-01,  5.7504e-02,  5.4488e-02, -9.7998e-02],
         [ 4.1489e-01, -3.4379e-01, -3.5539e-01,  9.9075e-01]],

        [[-1.5087e+00, -2.2464e-01,  2.6727e-02, -4.2099e-01],
         [ 1.5470e-01, -6.6959e-01, -2.5230e-01, -5.7251e-01],
         [-1.2495e-01,  2.5413e-01, -2.9930e-02,  4.8517e-02],
         [ 3.8806e-02, -8.9407e-01,  1.6918e-01,  4.8433e-05]],

        [[ 2.4978e-02, -8.4620e-01, -1.7038e+00, -1.3812e-01],
         [-3.9297e-01, -3.7726e-01, -2.1093e-02, -4.9845e-01],
         [-3.6471e-01, -3.3163e-01, -6.0916e-01,  1.4997e-02],
         [-4.3039e-01, -2.1968e-01,  5.2735e-02, -9.8434e-02]]],
       grad_fn=<ConvolutionBackward0>)

In [ ]:
key = torch.randn(3, 4)
print(key.size())
print(*key.size())

torch.Size([3, 4])
3 4


In [ ]:
batch_size = 2
time_steps = 3
embedding_dim = 4
inputx = torch.randn(batch_size, time_steps, embedding_dim)  # N*L*C

## pytorch中的梯度

In [ ]:
from torch.autograd import Variable

In [38]:
# pytorch 自定义autograd
class line(torch.autograd.Function):
    @staticmethod
    # 正向传播
    def forward(ctx, w, x, b):
        ctx.save_for_backward(w, x, b)
        return w * x + b

    @staticmethod
    # 反向传播
    def backward(ctx, grad_out):
        w, x, b = ctx.saved_tensors
        grad_w = grad_out * x
        grad_x = grad_out * w
        grad_b = grad_out

        return grad_w, grad_x, grad_b


w = torch.rand(2, 2, requires_grad=True)
x = torch.rand(2, 2, requires_grad=True)
b = torch.rand(2, 2, requires_grad=True)

# 正向传播得到out
out = line.apply(w, x, b)
out.backward(torch.ones(2, 2))

display(w, x, b)
display(w.grad, x.grad, b.grad)

tensor([[0.3666, 0.5533],
        [0.4492, 0.2403]], requires_grad=True)

tensor([[0.2259, 0.1686],
        [0.4962, 0.7516]], requires_grad=True)

tensor([[0.7682, 0.5979],
        [0.3391, 0.7125]], requires_grad=True)

tensor([[0.2259, 0.1686],
        [0.4962, 0.7516]])

tensor([[0.3666, 0.5533],
        [0.4492, 0.2403]])

tensor([[1., 1.],
        [1., 1.]])

In [43]:
# pytorch中grad的使用
x = torch.ones(2, 2, requires_grad=True)
x.register_hook(lambda grad:grad*2)

y = x + 2
z = y * y * 3

nn = torch.ones(2, 2)
display(nn)

# nn作为梯度的乘法因子
z.backward(gradient = nn, retain_graph=True)
torch.autograd.backward(z, grad_tensors=nn, retain_graph=True)

display(torch.autograd.grad(z, [x, y, z], grad_outputs=nn))
display(x.grad)

tensor([[1., 1.],
        [1., 1.]])

(tensor([[18., 18.],
         [18., 18.]]),
 tensor([[18., 18.],
         [18., 18.]]),
 tensor([[1., 1.],
         [1., 1.]]))

tensor([[72., 72.],
        [72., 72.]])

## hub模块

In [5]:
model = torch.hub.load('pytorch/vision', 'deeplabv3_resnet101', pretrained=True)
model.eval()

URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

In [7]:
import torch
model = torch.hub.load('pytorch/vision', 'alexnet', pretrained=True)
model.eval()


TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

# 归一化

In [ ]:
import torch
import torch.nn as nn

## batch_normalizion

对每个批量进行归一化

In [ ]:
# 调用batcch_norm API
# number of features or channels CC of the input
batch_norm_op = torch.nn.BatchNorm1d(embedding_dim, affine=False)  # 采用无偏归一化
bn_y = batch_norm_op(inputx.transpose(-1, -2)).transpose(-1, -2)
print(inputx)
print(bn_y)

tensor([[[ 0.2764,  1.2371, -1.1694,  1.9056],
         [-0.1912, -0.2005, -0.6737,  0.4105],
         [-0.6522, -0.0208, -1.2549, -0.1947]],

        [[ 0.5905,  0.6494,  0.8876,  1.0624],
         [ 0.3439, -0.1319, -2.0763, -1.5370],
         [-0.2877,  0.8809, -2.4044,  1.9477]]])
tensor([[[ 0.6180,  1.5178, -0.0509,  1.0686],
         [-0.4803, -1.0962,  0.4143, -0.1543],
         [-1.5635, -0.7694, -0.1311, -0.6492]],

        [[ 1.3561,  0.4491,  1.8793,  0.3790],
         [ 0.7768, -0.9714, -0.9019, -1.7471],
         [-0.7072,  0.8701, -1.2097,  1.1030]]])


In [ ]:
# 均值和方差
a = torch.randn(2, 3, 4)
print(a)
print(a.size())
b = a.mean((1), keepdim=False)  # 将第一维的所有数据相加求均值
print(b.size())
print(b)

tensor([[[-0.4218,  0.2444, -1.6615,  1.0068],
         [-0.5583, -0.4160,  0.7688, -0.2923],
         [-0.7681, -0.3263,  0.3474, -1.2080]],

        [[-0.1323, -0.1247, -0.0521, -0.4196],
         [ 0.2027,  0.0709,  0.4221, -0.5306],
         [ 0.4568, -2.0859,  2.2416,  2.0668]]])
torch.Size([2, 3, 4])
torch.Size([2, 4])
tensor([[-0.5827, -0.1659, -0.1818, -0.1645],
        [ 0.1757, -0.7132,  0.8705,  0.3722]])


## 均值和方差

均值和方差计算时计算某个维度的均值，该维度中所有的值都变为一个，其他维度不变

In [ ]:
a = torch.randn(2, 3, 4)
print(a)
b = a.std((1))
print(b)
print(b.size())

tensor([[[-0.1923,  0.6503,  0.0430, -0.8843],
         [ 0.4187,  1.1993,  0.2637,  0.7527],
         [-0.4696, -0.2032,  1.4352, -0.5672]],

        [[-0.8833, -0.3175, -0.0191,  0.7252],
         [ 1.1991, -1.6889,  0.1586, -1.1105],
         [-1.8764,  0.6856, -0.6121,  0.2912]]])
tensor([[0.4545, 0.7067, 0.7483, 0.8682],
        [1.5696, 1.1920, 0.4036, 0.9594]])
torch.Size([2, 4])


In [ ]:
# 实现batch_norm
bn_mean = inputx.mean((0, 1), keepdim=True)
bn_std = inputx.std((0, 1), keepdim=True, unbiased=False)
vertify_bn_y = (inputx - bn_mean) / (bn_std + 1e-5)
print(bn_y)
print(vertify_bn_y)

tensor([[[ 0.6180,  1.5178, -0.0509,  1.0686],
         [-0.4803, -1.0962,  0.4143, -0.1543],
         [-1.5635, -0.7694, -0.1311, -0.6492]],

        [[ 1.3561,  0.4491,  1.8793,  0.3790],
         [ 0.7768, -0.9714, -0.9019, -1.7471],
         [-0.7072,  0.8701, -1.2097,  1.1030]]])
tensor([[[ 0.6180,  1.5178, -0.0509,  1.0686],
         [-0.4803, -1.0961,  0.4143, -0.1543],
         [-1.5635, -0.7694, -0.1311, -0.6492]],

        [[ 1.3561,  0.4491,  1.8793,  0.3790],
         [ 0.7768, -0.9714, -0.9019, -1.7471],
         [-0.7072,  0.8701, -1.2097,  1.1030]]])


## layer_norm

对每一个样本进行归一化

In [ ]:
# api实现lay_norm
layer_norm_op = torch.nn.LayerNorm(embedding_dim, elementwise_affine=False)
ln_y = layer_norm_op(inputx)

In [ ]:
# 实现layer_norm
ln_mean = inputx.mean(dim=-1, keepdim=True)  # keepdim表示保持维度不会减少
print(ln_mean.size())
ln_std = inputx.std(dim=-1, keepdim=True, unbiased=False)
vertify_ln_y = (inputx - ln_mean) / (ln_std + 1e-5)
print(ln_y)
print(vertify_ln_y)

torch.Size([2, 3, 1])
tensor([[[-0.2016, -1.5521,  0.9563,  0.7974],
         [ 1.5631,  0.0544, -0.4585, -1.1590],
         [-0.2273,  1.6875, -0.8612, -0.5990]],

        [[ 0.7062, -0.9074, -1.0521,  1.2534],
         [-0.3024,  0.5005, -1.4478,  1.2497],
         [-1.0904, -0.6556,  1.5275,  0.2185]]])
tensor([[[-0.2016, -1.5521,  0.9563,  0.7974],
         [ 1.5631,  0.0544, -0.4585, -1.1590],
         [-0.2273,  1.6875, -0.8612, -0.5990]],

        [[ 0.7062, -0.9074, -1.0521,  1.2534],
         [-0.3024,  0.5005, -1.4478,  1.2497],
         [-1.0904, -0.6556,  1.5275,  0.2185]]])


## instance_norm

每个样本的每个维度

In [ ]:
# api
instance_norm_op = torch.nn.InstanceNorm1d(embedding_dim)
in_y = instance_norm_op(inputx.transpose(-1, -2)).transpose(-1, -2)

In [ ]:
# 动手
in_mean = inputx.mean(dim=1, keepdim=True)
in_std = inputx.std(dim=1, keepdim=True, unbiased=False)
vertify_in_y = (inputx - in_mean) / (in_std + 1e-5)
print(in_y)
print(vertify_in_y)

tensor([[[-0.2190, -1.2575,  0.9567,  1.1196],
         [ 1.3195,  1.1891,  0.4236,  0.1884],
         [-1.1005,  0.0683, -1.3803, -1.3080]],

        [[ 0.8484, -0.5451, -0.7319,  0.2044],
         [ 0.5556,  1.4027, -0.6820,  1.1097],
         [-1.4041, -0.8575,  1.4139, -1.3141]]])
tensor([[[-0.2190, -1.2575,  0.9567,  1.1196],
         [ 1.3195,  1.1891,  0.4236,  0.1884],
         [-1.1005,  0.0683, -1.3803, -1.3080]],

        [[ 0.8484, -0.5451, -0.7319,  0.2044],
         [ 0.5556,  1.4026, -0.6820,  1.1097],
         [-1.4041, -0.8575,  1.4139, -1.3141]]])


## group_norm

对每个样本的每个组进行归一化（要对样本向量进行分组）

In [ ]:
# api
num_group = 2
group_norm_op = torch.nn.GroupNorm(num_group, embedding_dim, affine=False)
gn_y = group_norm_op(inputx.transpose(-1, -2)).transpose(-1, -2)

In [ ]:
# 动手
groups_inputx = torch.split(
    inputx, split_size_or_sections=embedding_dim // num_group, dim=-1
)
result = []
for g_inputx in groups_inputx:
    gn_mean = g_inputx.mean(dim=(1, 2), keepdim=True)
    gn_std = g_inputx.std(dim=(1, 2), keepdim=True, unbiased=False)
    gn_result = (g_inputx - gn_mean) / (gn_std + 1e-5)
    result.append(gn_result)
vertify_gn_y = torch.cat(result, dim=-1)
print(gn_y)
print(vertify_gn_y)

tensor([[[-0.0331, -1.2634,  1.1040,  0.9467],
         [ 1.6584,  0.7907,  0.5323,  0.0944],
         [-1.0022, -0.1503, -1.4021, -1.2754]],

        [[ 0.8322, -0.6144, -1.0542,  0.7982],
         [ 0.5579,  1.4468, -1.0236,  1.6527],
         [-1.2775, -0.9450,  0.2620, -0.6351]]])
tensor([[[-0.0331, -1.2634,  1.1040,  0.9467],
         [ 1.6584,  0.7907,  0.5323,  0.0944],
         [-1.0022, -0.1503, -1.4021, -1.2754]],

        [[ 0.8322, -0.6144, -1.0542,  0.7982],
         [ 0.5579,  1.4468, -1.0236,  1.6527],
         [-1.2775, -0.9450,  0.2620, -0.6351]]])


## weight_norm

In [ ]:
# api
linear = nn.Linear(embedding_dim, 3, bias=False)
wn_linear = torch.nn.utils.weight_norm(linear)
wn_linear_output = wn_linear(inputx)
print(wn_linear_output.shape)
print(*wn_linear_output.size())

torch.Size([2, 3, 3])
2 3 3


In [ ]:
# 动手
print(linear.weight.shape)
weight_direction = linear.weight / (linear.weight.norm(dim=1, keepdim=True))
weight_magnitude = wn_linear.weight_g
print(weight_direction.shape)
print(weight_magnitude.shape)
vertify_wn_output = (
    inputx @ (weight_direction.transpose(-1, -2)) * (weight_magnitude.transpose(-1, -2))
)
print(wn_linear_output)
print(vertify_wn_output.shape)

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 1])
tensor([[[-0.6211, -1.2264, -0.2623],
         [-0.3892, -0.8806, -0.4603],
         [ 0.3847,  0.6419,  0.1565]],

        [[-0.1541, -0.2958, -0.4514],
         [ 0.5465, -0.4089, -0.7363],
         [-0.0882,  0.0252,  0.3594]]], grad_fn=<UnsafeViewBackward0>)
torch.Size([2, 3, 3])


## 点积和乘积

In [ ]:
a = torch.randint(1, 3, (2, 3))
b = torch.randint(1, 3, (2, 3))
print(a)
print(b)
print(a * b)  # 矩阵相应位置进行乘积
print(a @ b.transpose(-1, -2))  # 矩阵的点积

tensor([[1, 1, 1],
        [2, 2, 2]])
tensor([[2, 2, 2],
        [2, 2, 1]])
tensor([[2, 2, 2],
        [4, 4, 2]])
tensor([[ 6,  5],
        [12, 10]])


In [ ]:
print(3)

3


In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
class LinearClassifier(nn.Module):
    def __init__(self, input_size, num_classes):
        super(LinearClassifier, self).__init__()
        self.linear = nn.Linear(input_size, num_classes)

    def forward(self, x):
        out = self.linear(x)
        return out

In [3]:
# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert the data to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.long)

# Create DataLoader for training and testing sets
train_dataset = TensorDataset(X_train, y_train)
test_dataset = TensorDataset(X_test, y_test)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

In [4]:
input_size = 4
num_classes = 3
model = LinearClassifier(input_size, num_classes)

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [5]:
num_epochs = 100
for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(train_loader):
        outputs = model(inputs)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [10/100], Loss: 0.8231
Epoch [20/100], Loss: 0.4045
Epoch [30/100], Loss: 0.4878
Epoch [40/100], Loss: 0.5430
Epoch [50/100], Loss: 0.5410
Epoch [60/100], Loss: 0.4593
Epoch [70/100], Loss: 0.2255
Epoch [80/100], Loss: 0.5825
Epoch [90/100], Loss: 0.4099
Epoch [100/100], Loss: 0.2092


In [6]:
with torch.no_grad():
    correct = 0
    total = 0
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print(f'Accuracy of the model on the test set: {100 * correct / total:.2f}%')

Accuracy of the model on the test set: 90.00%
